### ISSUE TITLE
UniUtils object not available on the client.

### ISSUE THREAD

**Issue by JohnRodney** [vazco/meteor-universe-reactive-queries#2]
I like the package idea, but wasn't able to use as the UniUtils object isn't available when adding only this package to your App.

I added a PR to adjust the code #1

**Comment by cristo-rabani** [comment]
Thanks for fix

**Comment by JohnRodney** [comment]
@cristo-rabani has this been redeployed to atmosphere?  if so I'll remove my package from atmosphere.

**Comment by cristo-rabani** [comment]
Yes,  but also we add a few changes like update deps and there is new name.

**Comment by JohnRodney** [comment]
sounds good I'll test it first but looks like it'll work perfectly.
